<?php

function shift_cipher_menu() {
  $items['shift_cipher'] = array(
      'title' => 'Shift Cipher',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('shift_cipher_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
  );
  $items['shift_cipher_success_page'] = array(
      'title' => 'Success',
      'page callback' => 'shift_cipher_success',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );
  return $items;
}

function shift_cipher_form() {

  $form['shift_value'] = array(
      '#title' => 'Shift Value',
      '#type' => 'textfield',
      '#description' => t('Enter the number of positions to shift, must be a positive number'),
      '#element_validate' => array('element_validate_integer_positive'),
      '#required' => TRUE,
  );
  $form['direction'] = array(
      '#title' => 'Direction',
      '#type' => 'textfield',
      '#description' => t('Enter the direction you would like to shift, you must enter either right or left'),
      // '#element_validate' => array('element_validate_words'),
      '#required' => TRUE,
  );
  $form['phrase'] = array(
      '#title' => 'Phrase',
      '#type' => 'textfield',
      '#description' => t('Enter the phrase you would like ciphered'),
      '#required' => TRUE,
  );
  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Cipher',
  );

  return $form;
}


// function element_validate_words($element) {
//     if (($element['#value'] != 'right') || ($element['#value'] != 'left')) {
//       form_error($element, t("You must enter a valid direction, valid directions are 'right' or 'left'"));
//     }
// }

function shift_cipher_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['direction'];
    $phrase = $form_state['values']['phrase'];

    $phrase_lower = strtolower($phrase);
    $letters_array = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');
    $number_array = array_flip($letters_array);

    $phrase_array = str_split($phrase_lower);
    $phrase_count = count($phrase_array);
    $phrase_ciphered = '';

    for ($i = 0; $i < $phrase_count; $i++)
        $phrase_ciphered .= $letters_array[($number_array[$phrase_array[$i]] + $shift_value) %26];

          print_r($phrase_ciphered);
    $_SESSION['phrase_ciphered'] = $phrase_ciphered;

    $form_state['redirect'] = 'shift_cipher_success_page';

}

function shift_cipher_success() {
    $result = $_SESSION['$phrase_ciphered'];
    return $result;
}
